# Generated by Django 2.2.5 on 2020-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50, unique=True)),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=11)),
                ('nationality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, unique=True)),
                ('job_descrition', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
